version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  service1:
    build: ./service1
    container_name: service1
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    volumes:
      - ./service1:/app  
    environment:
      - RABBITMQ_HOST=rabbitmq

  service2:
    build: ./service2
    container_name: service2
    ports:
      - "8001:8001"
    volumes:
      - ./service2:/app  
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_FROM=${MAIL_FROM}
